"""Align ``references.bib`` and LaTeX inputs with M6 citation contract (stub merge + orphan bridge)."""

from __future__ import annotations

import logging
import re
from pathlib import Path

from articlebook.m2_stub_bib import bibtex_corpus
from articlebook.m6_qa_parse import (
    collect_tex_sources,
    extract_cite_keys_from_tex,
    parse_bib_keys,
)

log = logging.getLogger(__name__)

_BRIDGE_MARKER = "\\input{chapters/_bib_orphan_bridge}"
_BRIDGE_TEX = "chapters/_bib_orphan_bridge.tex"


def _split_stub_bib_entries_by_key() -> dict[str, str]:
    """Map BibTeX entry key -> full entry text (from curated M2 stub corpus)."""
    raw = bibtex_corpus().strip()
    out: dict[str, str] = {}
    for block in re.split(r"\n(?=@\w+\s*\{)", raw):
        block = block.strip()
        if not block:
            continue
        m = re.match(r"@\w+\s*\{\s*([^,\s]+)\s*,", block)
        if m:
            out[m.group(1).strip()] = block
    return out


def _normalize_nonstandard_bib_types(bib_text: str) -> str:
    """BibLaTeX/biber expects standard types; ``@entry`` is not portable."""
    return bib_text.replace("@entry{", "@misc{")


def merge_missing_stub_bib_entries(root: Path) -> list[str]:
    """Append stub ``.bib`` blocks for cite keys present in LaTeX but missing from ``references.bib``.

    Returns sorted list of keys that were merged.
    """
    latex = root / "latex"
    bib_path = latex / "references.bib"
    if not bib_path.is_file():
        return []
    bib_text = bib_path.read_text(encoding="utf-8", errors="replace")
    fixed = _normalize_nonstandard_bib_types(bib_text)
    if fixed != bib_text:
        bib_path.write_text(fixed, encoding="utf-8")
        bib_text = fixed
        log.info("bib_contract_align: normalized @entry->@misc in references.bib")

    bib_keys = parse_bib_keys(bib_text)
    tex_blob = collect_tex_sources(latex) if latex.is_dir() else ""
    cite_keys = extract_cite_keys_from_tex(tex_blob)
    missing = sorted(cite_keys - bib_keys)
    if not missing:
        return []
    stub_by_key = _split_stub_bib_entries_by_key()
    to_append: list[str] = []
    merged: list[str] = []
    for k in missing:
        block = stub_by_key.get(k)
        if not block:
            log.warning(
                "bib_contract_align: cite key %r has no stub .bib entry (skipping merge)", k
            )
            continue
        to_append.append(block.rstrip() + "\n")
        merged.append(k)
    if not to_append:
        return []
    sep = "\n" if not bib_text.endswith("\n") else ""
    bib_path.write_text(bib_text.rstrip() + sep + "\n".join(to_append) + "\n", encoding="utf-8")
    log.info("bib_contract_align: merged stub .bib keys %s", merged)
    return merged


def _orphan_keys(bib_text: str, tex_blob: str) -> list[str]:
    bib_keys = parse_bib_keys(bib_text)
    cite_keys = extract_cite_keys_from_tex(tex_blob)
    if re.search(r"\\nocite\{\*\}", tex_blob):
        return []
    return sorted(bib_keys - cite_keys)


def write_orphan_bib_bridge_and_patch_main(root: Path) -> None:
    """Cite orphan ``.bib`` keys via a tiny bridge chapter; patch ``main.tex`` to ``\\input`` it."""
    latex = root / "latex"
    main_tex = latex / "main.tex"
    bib_path = latex / "references.bib"
    ch_dir = latex / "chapters"
    bridge = ch_dir / "_bib_orphan_bridge.tex"
    if not main_tex.is_file() or not bib_path.is_file():
        return
    tex_blob = collect_tex_sources(latex)
    bib_text = bib_path.read_text(encoding="utf-8", errors="replace")
    orphans = _orphan_keys(bib_text, tex_blob)

    def strip_bridge_from_main(text: str) -> str:
        lines = [ln for ln in text.splitlines() if _BRIDGE_MARKER not in ln]
        return "\n".join(lines).rstrip() + "\n"

    main_body = main_tex.read_text(encoding="utf-8", errors="replace")
    if not orphans:
        if bridge.is_file():
            bridge.unlink()
        if _BRIDGE_MARKER in main_body:
            main_tex.write_text(strip_bridge_from_main(main_body), encoding="utf-8")
            log.info("bib_contract_align: removed orphan bridge (no uncited .bib keys)")
        return

    ch_dir.mkdir(parents=True, exist_ok=True)
    # Chunk keys so a single \parencite list stays readable for biber.
    chunks: list[str] = []
    for i in range(0, len(orphans), 12):
        part = ",".join(orphans[i : i + 12])
        chunks.append(rf"\parencite{{{part}}}")
    body = (
        "% Auto-generated by articlebook: cites .bib entries not referenced in chapter bodies.\n"
        r"\par\noindent\small\emph{Bibliography anchors (contract):} " + " ".join(chunks) + "\n"
    )
    bridge.write_text(body, encoding="utf-8")
    log.info("bib_contract_align: wrote %s for orphan keys %s", bridge.as_posix(), orphans)

    if _BRIDGE_MARKER not in main_body:
        patched = main_body.replace(
            "\\backmatter",
            _BRIDGE_MARKER + "\n\\backmatter",
            1,
        )
        if patched == main_body:
            log.warning("bib_contract_align: could not find \\backmatter in main.tex to patch")
        else:
            main_tex.write_text(patched, encoding="utf-8")
            log.info("bib_contract_align: patched main.tex with orphan bridge input")


def align_bib_with_tex_contract(root: Path) -> None:
    """Run after Markdown→TeX assembly: merge stub keys, normalize types, orphan bridge."""
    root = root.resolve()
    merge_missing_stub_bib_entries(root)
    write_orphan_bib_bridge_and_patch_main(root)
